name: backend-build

on:
  pull_request_target:
    types: [assigned, opened, synchronize, reopened]
    branches: [main]
    paths:
      - "app/**"
      
jobs:
  test:
    permissions: write-all
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: unit-test
        run: cd app && docker-compose -f docker-compose.tests.yml run -e NODE_OPTIONS=--unhandled-rejections=warn node npm run test:unit
      - name: upload test coverage report
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report-${{ github.event.pull_request.number }}
          path: app/coverage/
      - name: Jest Coverage Comment
        uses: MishaKav/jest-coverage-comment@main
        with:
          coverage-summary-path: ./app/coverage/coverage-summary.json
          coverage-path: ./app/coverage/coverage-report.txt