name: deploy-coverage-results

on:
  pull_request_target:
    types: [assigned, opened, synchronize, reopened]
    branches: [main]
    paths:
      - "app/**"

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: coverage-report-${{ github.event.pull_request.number }}
      - name: Monitor coverage
        uses: slavcodev/coverage-monitor-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          coverage_path: "app/coverage/clover.xml"
          threshold_alert: 10
          threshold_warning: 50
          threshold_metric: "lines"
